# E01-AutoPilot
cc_binary (
    name = "E01-AutoPilot",
    srcs = ["E01-AutoPilot.cpp"],
    copts = ["-Isrc/"],
    deps = ["//src:CGraph",],
)

#  E02-MockGUI
cc_binary (
    name = "E02-MockGUI",
    srcs = ["E02-MockGUI.cpp"],
    copts = ["-Isrc/"],
    deps = ["//src:CGraph",],
)

# E03-ThirdFlow
cc_binary (
    name = "E03-ThirdFlow",
    srcs = ["E03-ThirdFlow.cpp"],
    copts = ["-Isrc/"],
    deps = ["//src:CGraph",],
)

# E04-MapReduce
cc_binary (
    name = "E04-MapReduce",
    srcs = ["E04-MapReduce.cpp"],
    copts = ["-Isrc/"],
    deps = ["//src:CGraph",],
)

# E05-HttpServer
cc_binary (
    name = "E05-HttpServer",
    srcs = ["E05-HttpServer.cpp"],
    copts = ["-Isrc/"],
    deps = ["//src:CGraph",],
)

# E06-ParallelSort
cc_binary (
    name = "E06-ParallelSort",
    srcs = ["E06-ParallelSort.cpp"],
    copts = ["-Isrc/"],
    deps = ["//src:CGraph",],
)
